Add options to run_compile
Allow for entering configure options on the command line for run_compile. Also gives the
choice of the WRF experiment on the command line.
For WPS too.
Also moved optional environment variable declarations from build.env to run_compile

diff --git a/WPS/run_compile b/WPS/run_compile
--- a/WPS/run_compile
+++ b/WPS/run_compile
@@ -1,12 +1,4 @@
 #!/bin/bash
-#PBS -l walltime=1800
-#PBS -l mem=600MB
-#PBS -l ncpus=1
-#PBS -q express
-#PBS -l wd
-#PBS -j oe
-#PBS -l software=intel-compiler
-
 # You need to choose the configure option you wish to use and modify it in this file
 # Available options:
 # 1. serial code
@@ -14,14 +6,94 @@
 # 3. distributed memory code
 # 4. distributed memory code without GRIB2
 
+# Default values for command line options
+architecture=3
+clean=0
+help_text=0
+
+# Read in command line arguments (code is a mix from https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash and man getopt example) 
+SHORT=ha:c
+LONG=architecture:,help,clean
+
+PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+if [[ $? != 0 ]] ; then echo "Wrong arguments. Terminating..." >&2 ; exit 1 ; fi
+
+
+eval set -- "$PARSED"
+
+while true; do
+    case "$1" in
+	-a|--architecture) architecture="$2"; shift 2 ;;
+        -c|--clean) clean=1; shift ;;
+	-h|--help) help_text=1; shift ;;
+	--) shift; break ;;
+	*) echo "Programming error"; exit 1 ;;
+    esac
+done
+
+if [[ ${help_text} == 1 ]]; then
+    echo "The optional arguments are:"
+
+    # Architecture
+    echo "-a, --architecture  followed by a number (default 3). "
+    echo "    This is the input required by configure to choose the compilation options."
+    echo "    There are 4 different possibilities: "
+    echo "        1. serial code "
+    echo "        2. serial code without GRIB2"
+    echo "        3. distributed memory code"
+    echo "        4. distributed memory code without GRIB2"
+    
+    # Clean option
+    echo "-c, --clean   will call './clean -a' before configure and compilation"
+
+    # Help
+    echo "-h, --help  writes this help text"
+    exit 0
+fi
+
+# Some debugging outputs
+if [[ 0 == 1 ]]; then
+    echo "All the arguments values are: "
+    echo "architecture: "$architecture
+    echo "clean: "$clean
+    echo "help_text: "${help_text}
+    exit 1
+fi
+
+# Clean if asked for
+if [[ $clean == 1 ]]; then
+    ./clean -a
+fi
+
+# Source the modules
 source ../build.env
+
+# Load the JASPER environment variables if GRIB2 requested
+if [[ ${architecture} == 1 || ${architecture} == 3 ]]; then
+    export JASPERINC=/usr/include
+    export JASPERLIB=/usr/lib64
+fi
 
 # Option to change HERE!
 ./configure << EOF_configure
-4
+${architecture}
 EOF_configure
+
+qsub -N compile_wps <<EOF_compile
+#PBS -l walltime=1800
+#PBS -l mem=600MB
+#PBS -l ncpus=1
+#PBS -q express
+#PBS -l wd
+#PBS -j oe
+#PBS -l software=intel-compiler
+#PBS -W umask=0022
+
+source ../build.env
 
 ./compile
 ./compile plotfmt
 ./compile plotgrids
+
+EOF_compile
 
diff --git a/WRFV3/run_compile b/WRFV3/run_compile
--- a/WRFV3/run_compile
+++ b/WRFV3/run_compile
@@ -1,73 +1,178 @@
 #!/bin/bash
-#PBS -l walltime=1:00:00
-#PBS -l mem=5GB
-#PBS -l ncpus=4
-#PBS -j oe
-#PBS -q express
-#PBS -l wd
-#PBS -l software=intel-compiler
 
-# You need to specify WRF configuration options for running configure. 
-# Search for the line:
-# !!!! CONFIGURE OPTIONS HERE !!!!
-# to know where to input the options. You simply need to check the numbers
-# written after the configure line and make any change you'd like.
-#
-# Default is 7: optimised for Sandy Bridge (normal/express queues), distributed memory only.
-#
-# Here are the choices:
-#
-#Architecture options.
-#--------------------- 
-#There are 4 architectures possible. On each architecture, you can compile the code in 
-# 4 different ways (in that order):
-# - a. serial
-# - b. smpar (shared memory parallelisation)
-# - c. dmpar (distributed memory parallelisation)
-# - d. sm+dm (shared + distributed memory parallelisation)
-#
-# The architectures are:
-# - 1. best precision (options 1-4)
-# - 2. optimisation for Sandy Bridge processors (express/normal queues) (options 5-8)
-# - 3. optimisation for Broadwell processors (expressbw/normalbw queues) (options 9-12)
-# - 4. optimisation for Knights Landing processors (knl queue) (options 13-16)
-#
-#
-# E.g: To compile an optimised code for Broadwell processors, compiled with OpenMPI and OpenMP, 
-# you need to choose the option 12.
-#
-#Nest options:
-#-------------
-#1. basic
-#2. preset moves
-#3. vortex following
-#
-# 
-# You also need to check which case you want. By default,
-# this script will compile the real case. If you need to compile for
-# an idealised case, please change the value of the compile_case variable 
-#***********************************************************************
+#---------------------------------------
+# For help using this script please run:
+# ./run_compile -h
+#---------------------------------------
 
+#
+# Default values for variables populated by command-line argument
+debug=""
+opt=""
+chem=""
+help_text=0
 compile_case=em_real
+architecture=7
+nest=1
+clean=0
+netcdf4=0
 
+# Read in command line arguments (code is a mix from https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash and man getopt example) 
+SHORT=Ddsfha:n:c
+LONG=compile_case:,architecture:,nest:,help,chem,clean,netcdf4
+
+PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")
+if [[ $? != 0 ]] ; then echo "Wrong arguments. Terminating..." >&2 ; exit 1 ; fi
+
+
+eval set -- "$PARSED"
+
+while true; do
+    case "$1" in
+	-D) debug=-D; shift ;;
+	-d) debug=-d; shift ;;
+	-s) opt=-s; shift ;;
+	-f) opt=-f; shift ;;
+	--chem) chem=1; shift ;;
+	--compile_case) compile_case="$2"; shift 2 ;;
+	-a|--architecture) architecture="$2"; shift 2 ;;
+	-n|--nest) nest="$2"; shift 2 ;;
+        --netcdf4) netcdf4=1; shift ;;
+        -c|--clean) clean=1; shift ;;
+	-h|--help) help_text=1; shift ;;
+	--) shift; break ;;
+	*) echo "Programming error"; exit 1 ;;
+    esac
+done
+
+if [[ ${help_text} == 1 ]]; then
+    echo "The optional arguments are:"
+
+    # Architecture
+    echo "-a, --architecture  followed by a number (default 7). "
+    echo "    This is the first input required by configure to choose the compilation options."
+    echo "    There are 16 different possibilities. "
+    echo "    There are 4 processor options and each have 4 parallelisation options."
+    echo "    The parallelisation options are:"
+    echo "        serial  no parallelisation, runs on 1 processor"
+    echo "        smpar   shared memory parallelisation"
+    echo "        dmpar   distributed memory parallelisation"
+    echo "        sm+dm   shared and distributed memory parallelisation"
+    
+    echo "    The architecture choices are:"
+    echo "        1-4    best precision (1=serial, 2=smpar, 3=dmpar, 4=sm+dm)"
+    echo "        5-8    optimisation for Sandy Bridge processors (express/normal queues)"
+    echo "               (5=serial, 6=smpar, 7=dmpar, 8=sm+dm)"
+    echo "        9-12   optimisation for Broadwell processors (expressbw/normalbw queues)"
+    echo "               (9=serial, 10=smpar, 11=dmpar, 12=sm+dm)"
+    echo "        13-16  optimisation for Knights Landing processors (knl queue)"
+    echo "               (13=serial, 14=smpar, 15=dmpar, 16=sm+dm)"
+    echo 
+
+    # Nest
+    echo "-n, --nest  followed by a number (default 1)."
+    echo "    This option defines the type of nest used by WRF"
+    echo "        1   basic"
+    echo "        2   preset moves"
+    echo "        3   vortex following"
+    echo 
+
+    # To write compressed netCDF4 outputs
+    echo "-netcdf4   to output netCDF4, compressed files."
+    echo
+
+    # Debugging options
+    echo "-d   build with debugging information and no optimization" 
+    echo "-D   build with -d AND floating traps, traceback, uninitialized variables"
+    echo
+
+    # Optimisation options
+    echo "-s   build less modules with full optimisation options"
+    echo "-f   (default) build WRF with default level of optimisation"
+    echo
+
+    # Chemistry
+    echo "--chem  build WRF-Chem"
+    echo
+
+    # Compile case
+    echo "--compile_case  followed by the WRF case to build. Default is em_real"
+    echo
+
+    # Clean option
+    echo "-c, --clean   will call './clean -a' before configure and compilation"
+    echo
+
+    # Help
+    echo "-h, --help  writes this help text"
+    exit 0
+fi
+
+# Some debugging outputs
+if [[ 0 == 1 ]]; then
+    echo "All the arguments values are: "
+    echo "debug: "$debug
+    echo "opt: "$opt
+    echo "chem: "$chem
+    echo "compile_case: "$compile_case
+    echo "architecture: "$architecture
+    echo "nest: "$nest
+    echo "netcdf4: "$netcdf4
+    echo "clean: "$clean
+    echo "help_text: "${help_text}
+    exit 1
+fi
+
+# Source environment
 source ../build.env
+
+#netcdf4?
+if [[ $netcdf4 == 1 ]]; then
+    export NETCDF4=1
+fi
+
+# Clean if asked for
+if [[ $clean == 1 ]]; then
+    ./clean -a
+fi
 
 # WRF now supports large files per default. Option to turn off the support.
 #export WRFIO_NCD__NO_LARGE_FILE_SUPPORT=1
 
 # Un-comment to compile with chemistry
-#export WRF_CHEM=1
+if [[ $chem == 1 ]]; then
+    export WRF_CHEM=1
+    config_chem=chem
+fi
 
-# !!!! CONFIGURE OPTIONS HERE !!!!
-./configure << EOF_configure
-7
-1
+# run configure
+./configure $debug $opt $config_chem << EOF_configure
+$architecture
+$nest
 EOF_configure
 
+# submit compile to the queue.
+qsub -N compile_job <<EOF_compile
+#!/bin/bash
+#PBS -l walltime=1:00:00
+#PBS -l mem=10GB
+#PBS -l ncpus=8
+#PBS -j oe
+#PBS -q express
+#PBS -l wd
+#PBS -W umask=0022
+#PBS -l software=intel-compiler
+
+# Set the value of compile_case
+compile_case=${compile_case}
+
+# get the environment
+source ../build.env
+
 # For multi-processors compilation
-export J="-j $PBS_NCPUS"
+export J="-j \$PBS_NCPUS"
 
-echo #********************************************
-echo Start compilation of ${compile_case} for WRF.
-./compile ${compile_case}
-
+echo "#********************************************"
+echo Start compilation of \${compile_case} for WRF.
+./compile \${compile_case}
+EOF_compile
